### ISSUE TITLE
BUG: Email verification link is sus

### ISSUE THREAD

**Issue by StarrrLiteNL** [FPVScores/FPVScores#8] opened 2023-09-03 11:14 UTC
The link under the button of the account verification email gives me a bright red page with fishing warning in Chrome.

The short link under the button is fine and does not trigger this.

![image](https://github.com/FPVScores/FPVScores/assets/17098554/00951c8f-2f81-418c-b071-6cf508b6ac53)

**Comment by JesseFPV** [comment] 2023-09-03 14:22
Was caused by mail service using own domain smart urls. Disabled and should be fixed.

**Closed by JesseFPV** 2023-09-03 14:22 UTC
